baseURL = "https://polo871209.github.io"
languageCode = "en"

enableRobotsTXT = true
summaryLength = 0

[markup]
defaultMarkdownHandler = "goldmark"
[markup.highlight]
lineNos = true
noClasses = false

[pagination]
pagerSize = 15

[outputs]
home = ["HTML", "RSS", "JSON"]
