baseURL = "https://polo.is-not-a.dev"
languageCode = "en"

enableRobotsTXT = true
summaryLength = 0

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
lineNos = true
noClasses = false

[pagination]
pagerSize = 15

[outputs]
home = ["HTML", "RSS", "JSON"]
