title = "PoLoBlog"

[params.author]
name = "Po Lo 🌊"
image = "img/author.jpg"
headline = "Just my simple blog"
links = [
  { github = "https://github.com/polo871209" },
  { linkedin = "https://linkedin.com/in/polohi" },
  { email = "mailto:qazh0123@gmail.com" },
]
