[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Tags"
pageRef = "tags"
weight = 40


[[main]]
identifier = "search"
weight = 99
[main.params]
action = "search"
icon = "search"

[[footer]]
action = "appearance"
