colorScheme = "congo"

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

[footer]
showThemeAttribution = true
showAppearanceSwitcher = true

[homepage]
layout = "profile"

[article]
showDate = true
showDateUpdated = true
showAuthor = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = true
editURL = "https://github.com/polo871209/blog/tree/main/content/"
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showWordCount = false
showComments = false

[list]
showBreadcrumbs = true
showSummary = true
showTaxonomies = false
groupByYear = false
paginationWidth = 1
